name: concurro
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  
  cloudinary_dart: ^0.0.11
  cloudinary_api: ^1.0.0
  cloudinary_sdk: ^5.0.0+1
  fluttertoast: ^8.0.9

  intl: ^0.19.0

  geolocator: ^10.1.0
  google_maps_flutter: ^2.3.1
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  
  shake_gesture: ^1.1.0

  english_words: ^4.0.0
  
  provider: ^6.0.0
  sqflite: ^2.2.6
  path_provider: ^2.0.15
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.28

  firebase_core: ^3.10.0 # Required for Firebase initialization
  firebase_analytics: ^11.4.0 # Example Firebase library
  firebase_storage: ^12.4.0

  firebase_auth: ^5.4.0 # For authentication

  http: ^1.0.0

  cloud_firestore: ^5.6.1 # For Firestore database
  
  # Add more Firebase libraries as needed

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/navigation1.png
    - assets/icons/navigation2.png
    - assets/icons/navigation3.png
    - assets/icons/navigation4.png
    - assets/icons/navigation5.png
    - assets/user_image.png
    - assets/capture_button.png
    - assets/icons/heart_outline.png
    - assets/icons/heart_filled.png
    - assets/icons/comment_icon.png
    - assets/concurro.png